### ISSUE TITLE
is there a demo site ?

### ISSUE THREAD

**Issue by agerodol** [JohnMcLear/ep_slideshow#14]
I have installed ep_slideshow on my etherpad, and have really bad experience. Before describing an issue (there would be several) , I'd like to check the behaviour on a demo site, as it may very well be an installation problem.
However, the only link I have found on the Internet is http://beta.etherpad.org/p/slideshow?slideshow=true, refered from http://blog.etherpad.org/2013/04/29/introducing-really-real-time-collaborative-presentations/
but it seems ep_slideshow is not installed on this beta site.

thanx

**Comment by JohnMcLear** [comment]
Nope, feel free to create issues and bountys :)
