### ISSUE TITLE
behaviour different according to the way the slideshow is started

### ISSUE THREAD

**Issue by agerodol** [JohnMcLear/ep_slideshow#15]
I have installed ep_slideshow with ep_headings2 on an etherpad 13 (turnkey image).

when starting slideshow using url?slideshow=true:
- the pad is still editable, whether the option "edit when in slideshow view" is chosen or not
- the arrows do not change slide (they move cursor)

when starting slideshow using option "slideshow view"
- the pad is not editable unless the "edit" option is chosen
- I'm prompted for full screen or not

I've tried on firefox 34 on Linux and firefox 24 on Windows

**Comment by JohnMcLear** [comment]
This should be two issues.

1) Using URL: FIXED.  Please update and test.
2) Starting slideshow: Expected behaviour.

RE #2 Please create a new issue if you want different behaviour :) Thanks!

**Comment by agerodol** [comment]
Thanx
with new version 0.3.2, I still observe an issue when using URL:
if I choose url?slideshow=true
the pad is open with option "slideshow view" selected and "edit when in slideshow view" not selected, but the pad is editable.
if I click twice on  "edit when in slideshow view"  (selecting then unselecting) the behaviour is correct (as specified, left and right arrows allow to go through slides).

**Comment by JohnMcLear** [comment]
1) I cannot replicate this.
